# Generated by Django 2.2.6 on 2019-11-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20191031_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_picture',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_edited',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
