# Generated by Django 2.2.6 on 2019-11-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_auto_20191102_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='post_id',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
