# Generated by Django 2.2.6 on 2019-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.CharField(max_length=55, null=True, unique=True),
        ),
    ]
