# Generated by Django 2.2.6 on 2019-11-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_auto_20191104_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commented_user',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='user',
            new_name='liked_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='liked_user',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
