# Generated by Django 2.2.6 on 2019-11-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_auto_20191104_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='liked_user',
            new_name='disliked_user',
        ),
    ]
